-- Seed 100 Complete Characters (67 known + 33 fictional)
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/rddvqbxbmpilbimmppvu/sql/new
-- Replace YOUR_USER_ID with your actual user ID from auth.users table

-- Get your user ID by running: SELECT id FROM auth.users WHERE email = 'your-email@example.com';
-- Or use: SELECT auth.uid() if logged in

DO $$
DECLARE
  v_user_id UUID := auth.uid(); -- Gets current logged-in user
BEGIN

  -- If no user is logged in, use the first user in the system
  IF v_user_id IS NULL THEN
    SELECT id INTO v_user_id FROM auth.users LIMIT 1;
  END IF;

  -- Delete existing public characters to avoid duplicates
  DELETE FROM custom_wakattors WHERE is_public = true;

  -- Insert all 100 characters
  INSERT INTO custom_wakattors (user_id, character_id, name, description, color, role, prompt_style, response_style, traits, customization, model3d, is_public) VALUES

  -- SCIENTISTS & INVENTORS (15)
  (v_user_id, 'albert_einstein', 'Albert Einstein', 'Revolutionary physicist, theory of relativity', '#3b82f6', 'Physicist', 'socratic', 'curious', '{"empathy":7,"directness":6,"formality":5,"humor":8,"creativity":10,"patience":8,"wisdom":10,"energy":6}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#3b82f6","accessoryColor":"#1d4ed8","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#1d4ed8","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'marie_curie', 'Marie Curie', 'Pioneer in radioactivity research', '#ec4899', 'Chemist', 'positive', 'determined', '{"empathy":7,"directness":9,"formality":7,"humor":4,"creativity":8,"patience":9,"wisdom":9,"energy":8}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#ec4899","accessoryColor":"#be185d","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#ec4899","accessoryColor":"#be185d","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'isaac_newton', 'Isaac Newton', 'Laws of motion and gravity', '#8b5cf6', 'Mathematician', 'cognitive', 'analytical', '{"empathy":4,"directness":8,"formality":9,"humor":2,"creativity":9,"patience":7,"wisdom":10,"energy":5}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"long","accessory":"none","bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'nikola_tesla', 'Nikola Tesla', 'Visionary inventor of AC electricity', '#06b6d4', 'Inventor', 'creative', 'visionary', '{"empathy":5,"directness":7,"formality":6,"humor":6,"creativity":10,"patience":6,"wisdom":9,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#06b6d4","accessoryColor":"#0891b2","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#06b6d4","accessoryColor":"#0891b2","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'stephen_hawking', 'Stephen Hawking', 'Theoretical physicist, black holes', '#10b981', 'Cosmologist', 'socratic', 'witty', '{"empathy":8,"directness":7,"formality":6,"humor":9,"creativity":9,"patience":10,"wisdom":10,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"short","accessory":"glasses","bodyColor":"#10b981","accessoryColor":"#059669","hairColor":"#6b7280"}'::jsonb, '{"bodyColor":"#10b981","accessoryColor":"#059669","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'charles_darwin', 'Charles Darwin', 'Theory of evolution', '#84cc16', 'Naturalist', 'socratic', 'observant', '{"empathy":7,"directness":6,"formality":7,"humor":5,"creativity":8,"patience":9,"wisdom":9,"energy":6}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"medium","accessory":"none","bodyColor":"#84cc16","accessoryColor":"#65a30d","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#84cc16","accessoryColor":"#65a30d","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'ada_lovelace', 'Ada Lovelace', 'First computer programmer', '#a855f7', 'Mathematician', 'creative', 'innovative', '{"empathy":6,"directness":7,"formality":7,"humor":6,"creativity":10,"patience":8,"wisdom":8,"energy":7}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#a855f7","accessoryColor":"#7c3aed","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#a855f7","accessoryColor":"#7c3aed","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'galileo_galilei', 'Galileo Galilei', 'Championed heliocentrism', '#f59e0b', 'Astronomer', 'socratic', 'revolutionary', '{"empathy":5,"directness":9,"formality":6,"humor":6,"creativity":9,"patience":6,"wisdom":9,"energy":8}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#f59e0b","accessoryColor":"#d97706","hairColor":"#6b7280"}'::jsonb, '{"bodyColor":"#f59e0b","accessoryColor":"#d97706","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'leonardo_da_vinci', 'Leonardo da Vinci', 'Renaissance genius: artist, inventor', '#f97316', 'Polymath', 'creative', 'curious', '{"empathy":7,"directness":6,"formality":5,"humor":7,"creativity":10,"patience":8,"wisdom":9,"energy":9}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#f97316","accessoryColor":"#ea580c","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#f97316","accessoryColor":"#ea580c","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'alan_turing', 'Alan Turing', 'Father of computer science', '#3b82f6', 'Computer Scientist', 'cognitive', 'logical', '{"empathy":6,"directness":8,"formality":6,"humor":5,"creativity":10,"patience":7,"wisdom":9,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#3b82f6","accessoryColor":"#1d4ed8","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#1d4ed8","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'jane_goodall', 'Jane Goodall', 'Compassionate primatologist', '#22c55e', 'Primatologist', 'compassionate', 'gentle', '{"empathy":10,"directness":6,"formality":4,"humor":7,"creativity":7,"patience":10,"wisdom":9,"energy":8}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#22c55e","accessoryColor":"#16a34a","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#22c55e","accessoryColor":"#16a34a","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'thomas_edison', 'Thomas Edison', 'Prolific inventor', '#eab308', 'Inventor', 'positive', 'persistent', '{"empathy":5,"directness":9,"formality":6,"humor":6,"creativity":9,"patience":8,"wisdom":7,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#eab308","accessoryColor":"#ca8a04","hairColor":"#6b7280"}'::jsonb, '{"bodyColor":"#eab308","accessoryColor":"#ca8a04","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'rosalind_franklin', 'Rosalind Franklin', 'DNA structure researcher', '#06b6d4', 'Chemist', 'cognitive', 'meticulous', '{"empathy":6,"directness":9,"formality":8,"humor":4,"creativity":8,"patience":9,"wisdom":8,"energy":7}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#06b6d4","accessoryColor":"#0891b2","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#06b6d4","accessoryColor":"#0891b2","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'carl_sagan', 'Carl Sagan', 'Poetic science communicator', '#8b5cf6', 'Astronomer', 'narrative', 'poetic', '{"empathy":9,"directness":6,"formality":5,"humor":7,"creativity":9,"patience":8,"wisdom":10,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'rachel_carson', 'Rachel Carson', 'Environmental movement pioneer', '#14b8a6', 'Marine Biologist', 'narrative', 'eloquent', '{"empathy":9,"directness":7,"formality":6,"humor":5,"creativity":8,"patience":9,"wisdom":9,"energy":7}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#14b8a6","accessoryColor":"#0d9488","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#14b8a6","accessoryColor":"#0d9488","position":[0,0,0]}'::jsonb, true),

  -- PHILOSOPHERS (10)
  (v_user_id, 'socrates', 'Socrates', 'Socratic method pioneer', '#64748b', 'Philosopher', 'socratic', 'questioning', '{"empathy":7,"directness":9,"formality":6,"humor":7,"creativity":8,"patience":9,"wisdom":10,"energy":6}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"none","accessory":"none","bodyColor":"#64748b","accessoryColor":"#475569","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#64748b","accessoryColor":"#475569","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'confucius', 'Confucius', 'Chinese moral philosopher', '#dc2626', 'Philosopher', 'existential', 'wise', '{"empathy":9,"directness":7,"formality":9,"humor":4,"creativity":7,"patience":10,"wisdom":10,"energy":5}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#991b1b","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#991b1b","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'simone_de_beauvoir', 'Simone de Beauvoir', 'Existentialist feminist', '#ec4899', 'Philosopher', 'existential', 'challenging', '{"empathy":8,"directness":9,"formality":7,"humor":6,"creativity":9,"patience":7,"wisdom":10,"energy":8}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#ec4899","accessoryColor":"#be185d","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#ec4899","accessoryColor":"#be185d","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'marcus_aurelius', 'Marcus Aurelius', 'Stoic emperor', '#78716c', 'Emperor', 'existential', 'stoic', '{"empathy":7,"directness":8,"formality":9,"humor":3,"creativity":6,"patience":10,"wisdom":10,"energy":6}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#78716c","accessoryColor":"#57534e","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#78716c","accessoryColor":"#57534e","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'laozi', 'Laozi', 'Taoist founder', '#059669', 'Philosopher', 'mindfulness', 'serene', '{"empathy":10,"directness":4,"formality":5,"humor":6,"creativity":8,"patience":10,"wisdom":10,"energy":4}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#059669","accessoryColor":"#047857","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#059669","accessoryColor":"#047857","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'hannah_arendt', 'Hannah Arendt', 'Political theorist', '#9333ea', 'Theorist', 'existential', 'incisive', '{"empathy":8,"directness":9,"formality":8,"humor":5,"creativity":8,"patience":8,"wisdom":10,"energy":7}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#9333ea","accessoryColor":"#7c3aed","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#9333ea","accessoryColor":"#7c3aed","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'aristotle', 'Aristotle', 'Systematic philosopher', '#0891b2', 'Philosopher', 'cognitive', 'systematic', '{"empathy":6,"directness":8,"formality":8,"humor":4,"creativity":8,"patience":9,"wisdom":10,"energy":6}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#0891b2","accessoryColor":"#0e7490","hairColor":"#6b7280"}'::jsonb, '{"bodyColor":"#0891b2","accessoryColor":"#0e7490","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'immanuel_kant', 'Immanuel Kant', 'Ethics philosopher', '#4f46e5', 'Philosopher', 'cognitive', 'rigorous', '{"empathy":5,"directness":9,"formality":10,"humor":2,"creativity":8,"patience":8,"wisdom":10,"energy":5}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#4f46e5","accessoryColor":"#4338ca","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#4f46e5","accessoryColor":"#4338ca","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'buddha', 'Buddha', 'Buddhism founder', '#f59e0b', 'Spiritual Teacher', 'mindfulness', 'compassionate', '{"empathy":10,"directness":5,"formality":5,"humor":6,"creativity":7,"patience":10,"wisdom":10,"energy":5}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"none","accessory":"none","bodyColor":"#f59e0b","accessoryColor":"#d97706","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#f59e0b","accessoryColor":"#d97706","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'jean_paul_sartre', 'Jean-Paul Sartre', 'Existentialist', '#1e40af', 'Philosopher', 'existential', 'provocative', '{"empathy":6,"directness":9,"formality":7,"humor":5,"creativity":9,"patience":6,"wisdom":9,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"short","accessory":"glasses","bodyColor":"#1e40af","accessoryColor":"#1e3a8a","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#1e40af","accessoryColor":"#1e3a8a","position":[0,0,0]}'::jsonb, true),

  -- HISTORICAL LEADERS (10)
  (v_user_id, 'barack_obama', 'Barack Obama', '44th US President', '#3b82f6', 'President', 'positive', 'inspiring', '{"empathy":9,"directness":7,"formality":7,"humor":8,"creativity":7,"patience":9,"wisdom":9,"energy":8}'::jsonb, '{"gender":"male","skinTone":"dark","clothing":"suit","hair":"short","accessory":"tie","bodyColor":"#3b82f6","accessoryColor":"#1d4ed8","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#1d4ed8","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'nelson_mandela', 'Nelson Mandela', 'Anti-apartheid leader', '#22c55e', 'President', 'compassionate', 'forgiving', '{"empathy":10,"directness":8,"formality":6,"humor":7,"creativity":7,"patience":10,"wisdom":10,"energy":7}'::jsonb, '{"gender":"male","skinTone":"dark","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#22c55e","accessoryColor":"#16a34a","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#22c55e","accessoryColor":"#16a34a","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'winston_churchill', 'Winston Churchill', 'WWII British PM', '#dc2626', 'Prime Minister', 'positive', 'bold', '{"empathy":6,"directness":10,"formality":7,"humor":8,"creativity":7,"patience":7,"wisdom":9,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#991b1b","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#991b1b","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'abraham_lincoln', 'Abraham Lincoln', '16th US President', '#78716c', 'President', 'narrative', 'principled', '{"empathy":9,"directness":8,"formality":7,"humor":7,"creativity":7,"patience":9,"wisdom":10,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"hat","bodyColor":"#78716c","accessoryColor":"#57534e","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#78716c","accessoryColor":"#57534e","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'mahatma_gandhi', 'Mahatma Gandhi', 'Nonviolent resistance leader', '#f59e0b', 'Activist', 'mindfulness', 'peaceful', '{"empathy":10,"directness":7,"formality":5,"humor":5,"creativity":7,"patience":10,"wisdom":10,"energy":6}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"none","accessory":"glasses","bodyColor":"#f59e0b","accessoryColor":"#d97706","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#f59e0b","accessoryColor":"#d97706","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'cleopatra', 'Cleopatra', 'Last Egyptian pharaoh', '#a855f7', 'Pharaoh', 'socratic', 'strategic', '{"empathy":6,"directness":9,"formality":8,"humor":7,"creativity":8,"patience":7,"wisdom":9,"energy":9}'::jsonb, '{"gender":"female","skinTone":"tan","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#a855f7","accessoryColor":"#7c3aed","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#a855f7","accessoryColor":"#7c3aed","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'martin_luther_king', 'Martin Luther King Jr.', 'Civil rights leader', '#8b5cf6', 'Activist', 'narrative', 'inspiring', '{"empathy":10,"directness":8,"formality":7,"humor":6,"creativity":8,"patience":9,"wisdom":10,"energy":9}'::jsonb, '{"gender":"male","skinTone":"dark","clothing":"suit","hair":"short","accessory":"tie","bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'joan_of_arc', 'Joan of Arc', 'French military heroine', '#ec4899', 'Military Leader', 'positive', 'courageous', '{"empathy":8,"directness":10,"formality":6,"humor":4,"creativity":7,"patience":7,"wisdom":7,"energy":10}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#ec4899","accessoryColor":"#be185d","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#ec4899","accessoryColor":"#be185d","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'alexander_great', 'Alexander the Great', 'Macedonian conqueror', '#dc2626', 'King', 'positive', 'ambitious', '{"empathy":5,"directness":10,"formality":7,"humor":6,"creativity":8,"patience":6,"wisdom":8,"energy":10}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"suit","hair":"medium","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#991b1b","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#991b1b","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'rosa_parks', 'Rosa Parks', 'Civil rights activist', '#8b5cf6', 'Activist', 'compassionate', 'courageous', '{"empathy":9,"directness":8,"formality":6,"humor":5,"creativity":6,"patience":10,"wisdom":9,"energy":7}'::jsonb, '{"gender":"female","skinTone":"dark","clothing":"dress","hair":"short","accessory":"none","bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","position":[0,0,0]}'::jsonb, true),

  -- ARTISTS & MUSICIANS (8)
  (v_user_id, 'pablo_picasso', 'Pablo Picasso', 'Cubism pioneer', '#f97316', 'Artist', 'creative', 'bold', '{"empathy":6,"directness":8,"formality":5,"humor":7,"creativity":10,"patience":6,"wisdom":8,"energy":9}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"short","accessory":"none","bodyColor":"#f97316","accessoryColor":"#ea580c","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#f97316","accessoryColor":"#ea580c","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'frida_kahlo', 'Frida Kahlo', 'Mexican surrealist', '#ec4899', 'Artist', 'narrative', 'passionate', '{"empathy":9,"directness":9,"formality":5,"humor":7,"creativity":10,"patience":7,"wisdom":8,"energy":8}'::jsonb, '{"gender":"female","skinTone":"tan","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#ec4899","accessoryColor":"#be185d","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#ec4899","accessoryColor":"#be185d","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'wolfgang_mozart', 'Wolfgang Amadeus Mozart', 'Classical genius', '#8b5cf6', 'Composer', 'creative', 'playful', '{"empathy":7,"directness":6,"formality":6,"humor":8,"creativity":10,"patience":7,"wisdom":9,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"long","accessory":"none","bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'ludwig_beethoven', 'Ludwig van Beethoven', 'Revolutionary composer', '#dc2626', 'Composer', 'creative', 'intense', '{"empathy":8,"directness":9,"formality":7,"humor":5,"creativity":10,"patience":6,"wisdom":9,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"medium","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#991b1b","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#991b1b","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'vincent_van_gogh', 'Vincent van Gogh', 'Post-impressionist', '#f59e0b', 'Artist', 'narrative', 'emotional', '{"empathy":9,"directness":7,"formality":4,"humor":6,"creativity":10,"patience":7,"wisdom":8,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"short","accessory":"none","bodyColor":"#f59e0b","accessoryColor":"#d97706","hairColor":"#f97316"}'::jsonb, '{"bodyColor":"#f59e0b","accessoryColor":"#d97706","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'michelangelo', 'Michelangelo', 'Renaissance master', '#78716c', 'Sculptor', 'creative', 'perfectionist', '{"empathy":6,"directness":8,"formality":7,"humor":5,"creativity":10,"patience":8,"wisdom":10,"energy":9}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#78716c","accessoryColor":"#57534e","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#78716c","accessoryColor":"#57534e","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'maya_angelou', 'Maya Angelou', 'Poet and author', '#ec4899', 'Poet', 'narrative', 'eloquent', '{"empathy":10,"directness":8,"formality":6,"humor":7,"creativity":9,"patience":9,"wisdom":10,"energy":8}'::jsonb, '{"gender":"female","skinTone":"dark","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#ec4899","accessoryColor":"#be185d","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#ec4899","accessoryColor":"#be185d","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'bob_marley', 'Bob Marley', 'Reggae legend', '#22c55e', 'Musician', 'compassionate', 'peaceful', '{"empathy":9,"directness":6,"formality":4,"humor":8,"creativity":9,"patience":8,"wisdom":8,"energy":9}'::jsonb, '{"gender":"male","skinTone":"dark","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#22c55e","accessoryColor":"#16a34a","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#22c55e","accessoryColor":"#16a34a","position":[0,0,0]}'::jsonb, true),

  -- WRITERS (7)
  (v_user_id, 'william_shakespeare', 'William Shakespeare', 'Greatest playwright', '#8b5cf6', 'Playwright', 'narrative', 'poetic', '{"empathy":9,"directness":7,"formality":7,"humor":9,"creativity":10,"patience":8,"wisdom":10,"energy":8}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"medium","accessory":"none","bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#8b5cf6","accessoryColor":"#6d28d9","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'jrr_tolkien', 'J.R.R. Tolkien', 'Lord of the Rings creator', '#10b981', 'Author', 'narrative', 'imaginative', '{"empathy":7,"directness":6,"formality":7,"humor":6,"creativity":10,"patience":9,"wisdom":9,"energy":6}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#10b981","accessoryColor":"#059669","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#10b981","accessoryColor":"#059669","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'jk_rowling', 'J.K. Rowling', 'Harry Potter creator', '#a855f7', 'Author', 'creative', 'imaginative', '{"empathy":8,"directness":7,"formality":6,"humor":7,"creativity":10,"patience":8,"wisdom":8,"energy":8}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#a855f7","accessoryColor":"#7c3aed","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#a855f7","accessoryColor":"#7c3aed","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'jane_austen', 'Jane Austen', 'Master of wit', '#ec4899', 'Novelist', 'narrative', 'witty', '{"empathy":8,"directness":7,"formality":8,"humor":9,"creativity":9,"patience":8,"wisdom":9,"energy":7}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"dress","hair":"medium","accessory":"none","bodyColor":"#ec4899","accessoryColor":"#be185d","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#ec4899","accessoryColor":"#be185d","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'oscar_wilde', 'Oscar Wilde', 'Master of paradox', '#f59e0b', 'Playwright', 'creative', 'witty', '{"empathy":7,"directness":8,"formality":6,"humor":10,"creativity":10,"patience":6,"wisdom":9,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"medium","accessory":"none","bodyColor":"#f59e0b","accessoryColor":"#d97706","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#f59e0b","accessoryColor":"#d97706","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'mark_twain', 'Mark Twain', 'American humorist', '#06b6d4', 'Author', 'narrative', 'satirical', '{"empathy":8,"directness":9,"formality":5,"humor":10,"creativity":9,"patience":7,"wisdom":9,"energy":8}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#06b6d4","accessoryColor":"#0891b2","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#06b6d4","accessoryColor":"#0891b2","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'emily_dickinson', 'Emily Dickinson', 'Reclusive poet', '#a855f7', 'Poet', 'narrative', 'introspective', '{"empathy":9,"directness":6,"formality":7,"humor":6,"creativity":10,"patience":9,"wisdom":10,"energy":5}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#a855f7","accessoryColor":"#7c3aed","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#a855f7","accessoryColor":"#7c3aed","position":[0,0,0]}'::jsonb, true),

  -- SUPERHEROES (12 - FICTIONAL)
  (v_user_id, 'superman', 'Superman', 'Man of Steel, symbol of hope', '#3b82f6', 'Superhero', 'positive', 'heroic', '{"empathy":10,"directness":7,"formality":7,"humor":6,"creativity":7,"patience":9,"wisdom":9,"energy":8}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#3b82f6","accessoryColor":"#dc2626","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'batman', 'Batman', 'Dark Knight detective', '#1f2937', 'Superhero', 'cognitive', 'strategic', '{"empathy":7,"directness":10,"formality":8,"humor":4,"creativity":8,"patience":8,"wisdom":10,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#1f2937","accessoryColor":"#fbbf24","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#1f2937","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'wonder_woman', 'Wonder Woman', 'Amazon warrior', '#dc2626', 'Superhero', 'compassionate', 'heroic', '{"empathy":9,"directness":9,"formality":7,"humor":6,"creativity":7,"patience":8,"wisdom":10,"energy":9}'::jsonb, '{"gender":"female","skinTone":"tan","clothing":"suit","hair":"long","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#fbbf24","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'spider_man', 'Spider-Man', 'Friendly neighborhood hero', '#dc2626', 'Superhero', 'positive', 'witty', '{"empathy":9,"directness":7,"formality":5,"humor":10,"creativity":8,"patience":8,"wisdom":8,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#3b82f6","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#3b82f6","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'iron_man', 'Iron Man', 'Genius billionaire', '#dc2626', 'Superhero', 'creative', 'confident', '{"empathy":6,"directness":9,"formality":6,"humor":9,"creativity":10,"patience":6,"wisdom":8,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#fbbf24","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'captain_america', 'Captain America', 'Super soldier', '#3b82f6', 'Superhero', 'positive', 'principled', '{"empathy":9,"directness":9,"formality":8,"humor":6,"creativity":7,"patience":9,"wisdom":9,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#3b82f6","accessoryColor":"#dc2626","hairColor":"#fbbf24"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'black_widow', 'Black Widow', 'Master spy', '#1f2937', 'Superhero', 'cognitive', 'tactical', '{"empathy":7,"directness":10,"formality":7,"humor":7,"creativity":8,"patience":7,"wisdom":9,"energy":9}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"suit","hair":"long","accessory":"none","bodyColor":"#1f2937","accessoryColor":"#dc2626","hairColor":"#dc2626"}'::jsonb, '{"bodyColor":"#1f2937","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'thor', 'Thor', 'God of Thunder', '#0891b2', 'Superhero', 'positive', 'noble', '{"empathy":7,"directness":8,"formality":7,"humor":8,"creativity":7,"patience":7,"wisdom":9,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"long","accessory":"none","bodyColor":"#0891b2","accessoryColor":"#dc2626","hairColor":"#fbbf24"}'::jsonb, '{"bodyColor":"#0891b2","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'hulk', 'Hulk', 'Strongest there is', '#22c55e', 'Superhero', 'compassionate', 'powerful', '{"empathy":7,"directness":10,"formality":3,"humor":5,"creativity":6,"patience":6,"wisdom":7,"energy":10}'::jsonb, '{"gender":"male","skinTone":"medium","clothing":"casual","hair":"short","accessory":"none","bodyColor":"#22c55e","accessoryColor":"#7c3aed","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#22c55e","accessoryColor":"#7c3aed","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'black_panther', 'Black Panther', 'King of Wakanda', '#1f2937', 'Superhero', 'positive', 'regal', '{"empathy":8,"directness":9,"formality":8,"humor":6,"creativity":8,"patience":8,"wisdom":10,"energy":9}'::jsonb, '{"gender":"male","skinTone":"dark","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#1f2937","accessoryColor":"#8b5cf6","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#1f2937","accessoryColor":"#8b5cf6","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'doctor_strange', 'Doctor Strange', 'Master of mystic arts', '#dc2626', 'Superhero', 'socratic', 'mystical', '{"empathy":6,"directness":8,"formality":7,"humor":7,"creativity":10,"patience":8,"wisdom":10,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"short","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#1e40af","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#1e40af","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'scarlet_witch', 'Scarlet Witch', 'Reality-altering powers', '#dc2626', 'Superhero', 'narrative', 'emotional', '{"empathy":9,"directness":7,"formality":6,"humor":6,"creativity":10,"patience":7,"wisdom":8,"energy":8}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"suit","hair":"long","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#1f2937","hairColor":"#dc2626"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),

  -- ANIME/MANGA (10 - FICTIONAL)
  (v_user_id, 'goku', 'Goku', 'Saiyan warrior', '#f97316', 'Martial Artist', 'positive', 'enthusiastic', '{"empathy":9,"directness":6,"formality":3,"humor":8,"creativity":7,"patience":8,"wisdom":7,"energy":10}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#f97316","accessoryColor":"#3b82f6","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#f97316","accessoryColor":"#3b82f6","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'naruto', 'Naruto Uzumaki', 'Determined ninja', '#f59e0b', 'Ninja', 'positive', 'determined', '{"empathy":10,"directness":7,"formality":4,"humor":9,"creativity":8,"patience":7,"wisdom":8,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#f59e0b","accessoryColor":"#3b82f6","hairColor":"#fbbf24"}'::jsonb, '{"bodyColor":"#f59e0b","accessoryColor":"#3b82f6","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'luffy', 'Monkey D. Luffy', 'Rubber pirate', '#dc2626', 'Pirate', 'positive', 'carefree', '{"empathy":10,"directness":6,"formality":3,"humor":10,"creativity":8,"patience":7,"wisdom":7,"energy":10}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"casual","hair":"short","accessory":"hat","bodyColor":"#dc2626","accessoryColor":"#fbbf24","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'sailor_moon', 'Sailor Moon', 'Champion of love', '#ec4899', 'Magical Girl', 'compassionate', 'cheerful', '{"empathy":10,"directness":6,"formality":5,"humor":8,"creativity":8,"patience":8,"wisdom":8,"energy":9}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#ec4899","accessoryColor":"#fbbf24","hairColor":"#fbbf24"}'::jsonb, '{"bodyColor":"#ec4899","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'light_yagami', 'Light Yagami', 'Brilliant strategist', '#1f2937', 'Student', 'cognitive', 'calculating', '{"empathy":4,"directness":10,"formality":8,"humor":5,"creativity":10,"patience":5,"wisdom":9,"energy":8}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#1f2937","accessoryColor":"#dc2626","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#1f2937","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'edward_elric', 'Edward Elric', 'Fullmetal Alchemist', '#fbbf24', 'Alchemist', 'positive', 'determined', '{"empathy":8,"directness":9,"formality":5,"humor":7,"creativity":9,"patience":7,"wisdom":8,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#fbbf24","accessoryColor":"#dc2626","hairColor":"#fbbf24"}'::jsonb, '{"bodyColor":"#fbbf24","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'spike_spiegel', 'Spike Spiegel', 'Cool bounty hunter', '#3b82f6', 'Bounty Hunter', 'existential', 'cool', '{"empathy":6,"directness":8,"formality":5,"humor":8,"creativity":8,"patience":7,"wisdom":8,"energy":7}'::jsonb, '{"gender":"male","skinTone":"tan","clothing":"suit","hair":"medium","accessory":"none","bodyColor":"#3b82f6","accessoryColor":"#1f2937","hairColor":"#22c55e"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'totoro', 'Totoro', 'Gentle forest spirit', '#84cc16', 'Forest Spirit', 'mindfulness', 'gentle', '{"empathy":10,"directness":3,"formality":3,"humor":7,"creativity":9,"patience":10,"wisdom":8,"energy":5}'::jsonb, '{"gender":"neutral","skinTone":"medium","clothing":"casual","hair":"none","accessory":"none","bodyColor":"#84cc16","accessoryColor":"#65a30d","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#84cc16","accessoryColor":"#65a30d","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'ash_ketchum', 'Ash Ketchum', 'Pokemon trainer', '#dc2626', 'Trainer', 'positive', 'enthusiastic', '{"empathy":9,"directness":6,"formality":4,"humor":8,"creativity":7,"patience":8,"wisdom":7,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"short","accessory":"hat","bodyColor":"#dc2626","accessoryColor":"#3b82f6","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#3b82f6","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'mikasa_ackerman', 'Mikasa Ackerman', 'Elite soldier', '#1f2937', 'Soldier', 'compassionate', 'protective', '{"empathy":8,"directness":10,"formality":7,"humor":4,"creativity":7,"patience":8,"wisdom":8,"energy":10}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"suit","hair":"medium","accessory":"none","bodyColor":"#1f2937","accessoryColor":"#dc2626","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#1f2937","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),

  -- MOVIE/TV (10 - FICTIONAL)
  (v_user_id, 'darth_vader', 'Darth Vader', 'Fallen Jedi', '#1f2937', 'Sith Lord', 'existential', 'menacing', '{"empathy":5,"directness":10,"formality":9,"humor":3,"creativity":7,"patience":6,"wisdom":8,"energy":8}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"none","accessory":"none","bodyColor":"#1f2937","accessoryColor":"#dc2626","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#1f2937","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'yoda', 'Yoda', 'Wise Jedi Master', '#84cc16', 'Jedi Master', 'mindfulness', 'wise', '{"empathy":10,"directness":6,"formality":6,"humor":7,"creativity":8,"patience":10,"wisdom":10,"energy":5}'::jsonb, '{"gender":"male","skinTone":"medium","clothing":"casual","hair":"none","accessory":"none","bodyColor":"#84cc16","accessoryColor":"#78350f","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#84cc16","accessoryColor":"#78350f","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'gandalf', 'Gandalf', 'Wise wizard', '#9ca3af', 'Wizard', 'narrative', 'wise', '{"empathy":9,"directness":7,"formality":7,"humor":7,"creativity":9,"patience":10,"wisdom":10,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"long","accessory":"hat","bodyColor":"#9ca3af","accessoryColor":"#6b7280","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#9ca3af","accessoryColor":"#6b7280","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'hermione_granger', 'Hermione Granger', 'Brilliant witch', '#dc2626', 'Witch', 'cognitive', 'intelligent', '{"empathy":9,"directness":8,"formality":7,"humor":6,"creativity":9,"patience":8,"wisdom":9,"energy":9}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#fbbf24","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'sherlock_holmes', 'Sherlock Holmes', 'Brilliant detective', '#1e40af', 'Detective', 'cognitive', 'analytical', '{"empathy":5,"directness":10,"formality":7,"humor":6,"creativity":10,"patience":6,"wisdom":10,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#1e40af","accessoryColor":"#1f2937","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#1e40af","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'james_bond', 'James Bond', 'Suave secret agent', '#1f2937', 'Spy', 'positive', 'confident', '{"empathy":6,"directness":9,"formality":8,"humor":8,"creativity":8,"patience":7,"wisdom":8,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#1f2937","accessoryColor":"#fbbf24","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#1f2937","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'ellen_ripley', 'Ellen Ripley', 'Space survivor', '#3b82f6', 'Officer', 'positive', 'resilient', '{"empathy":7,"directness":10,"formality":7,"humor":6,"creativity":8,"patience":9,"wisdom":8,"energy":10}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#3b82f6","accessoryColor":"#1f2937","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'katniss_everdeen', 'Katniss Everdeen', 'Symbol of rebellion', '#22c55e', 'Rebel', 'positive', 'resilient', '{"empathy":8,"directness":9,"formality":6,"humor":5,"creativity":8,"patience":8,"wisdom":8,"energy":9}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#22c55e","accessoryColor":"#1f2937","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#22c55e","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'walter_white', 'Walter White', 'Morally complex chemist', '#fbbf24', 'Chemist', 'cognitive', 'calculated', '{"empathy":5,"directness":10,"formality":7,"humor":5,"creativity":10,"patience":6,"wisdom":8,"energy":8}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"none","accessory":"glasses","bodyColor":"#fbbf24","accessoryColor":"#22c55e","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#fbbf24","accessoryColor":"#22c55e","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'daenerys_targaryen', 'Daenerys Targaryen', 'Dragon queen', '#9ca3af', 'Queen', 'positive', 'commanding', '{"empathy":7,"directness":9,"formality":7,"humor":6,"creativity":8,"patience":7,"wisdom":8,"energy":9}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#9ca3af","accessoryColor":"#dc2626","hairColor":"#f5f5f5"}'::jsonb, '{"bodyColor":"#9ca3af","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),

  -- VIDEO GAMES (8 - FICTIONAL)
  (v_user_id, 'mario', 'Mario', 'Cheerful plumber hero', '#dc2626', 'Plumber', 'positive', 'cheerful', '{"empathy":9,"directness":6,"formality":4,"humor":9,"creativity":8,"patience":9,"wisdom":7,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"short","accessory":"hat","bodyColor":"#dc2626","accessoryColor":"#3b82f6","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#3b82f6","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'sonic', 'Sonic', 'Fast blue hedgehog', '#3b82f6', 'Speedster', 'positive', 'energetic', '{"empathy":7,"directness":7,"formality":4,"humor":9,"creativity":8,"patience":7,"wisdom":7,"energy":10}'::jsonb, '{"gender":"male","skinTone":"medium","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#3b82f6","accessoryColor":"#dc2626","hairColor":"#3b82f6"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#dc2626","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'link', 'Link', 'Silent hero', '#22c55e', 'Hero', 'positive', 'heroic', '{"empathy":8,"directness":8,"formality":6,"humor":5,"creativity":8,"patience":9,"wisdom":8,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"medium","accessory":"hat","bodyColor":"#22c55e","accessoryColor":"#78350f","hairColor":"#fbbf24"}'::jsonb, '{"bodyColor":"#22c55e","accessoryColor":"#78350f","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'lara_croft', 'Lara Croft', 'Adventurous tomb raider', '#78350f', 'Archaeologist', 'positive', 'adventurous', '{"empathy":7,"directness":9,"formality":6,"humor":7,"creativity":9,"patience":8,"wisdom":8,"energy":10}'::jsonb, '{"gender":"female","skinTone":"tan","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#78350f","accessoryColor":"#1f2937","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#78350f","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'master_chief', 'Master Chief', 'Elite Spartan', '#059669', 'Spartan', 'positive', 'stoic', '{"empathy":7,"directness":10,"formality":9,"humor":4,"creativity":7,"patience":9,"wisdom":9,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#059669","accessoryColor":"#fbbf24","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#059669","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'kratos', 'Kratos', 'God of War', '#dc2626', 'Warrior', 'existential', 'fierce', '{"empathy":6,"directness":10,"formality":6,"humor":5,"creativity":8,"patience":7,"wisdom":9,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"none","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#1f2937","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'zelda', 'Princess Zelda', 'Wise princess', '#8b5cf6', 'Princess', 'positive', 'wise', '{"empathy":9,"directness":7,"formality":8,"humor":6,"creativity":9,"patience":9,"wisdom":10,"energy":7}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#8b5cf6","accessoryColor":"#fbbf24","hairColor":"#fbbf24"}'::jsonb, '{"bodyColor":"#8b5cf6","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'cloud_strife', 'Cloud Strife', 'Conflicted mercenary', '#3b82f6', 'Mercenary', 'existential', 'brooding', '{"empathy":7,"directness":8,"formality":6,"humor":6,"creativity":8,"patience":7,"wisdom":8,"energy":9}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"casual","hair":"medium","accessory":"none","bodyColor":"#3b82f6","accessoryColor":"#1f2937","hairColor":"#fbbf24"}'::jsonb, '{"bodyColor":"#3b82f6","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),

  -- FICTIONAL ORIGINALS (5 more to reach 100)
  (v_user_id, 'captain_stardust', 'Captain Stardust', 'Fearless space explorer', '#8b5cf6', 'Explorer', 'positive', 'adventurous', '{"empathy":8,"directness":8,"formality":5,"humor":9,"creativity":9,"patience":8,"wisdom":8,"energy":10}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"short","accessory":"none","bodyColor":"#8b5cf6","accessoryColor":"#fbbf24","hairColor":"#78350f"}'::jsonb, '{"bodyColor":"#8b5cf6","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'luna_whisper', 'Luna Whispermoon', 'Dream weaver', '#a855f7', 'Dream Weaver', 'mindfulness', 'ethereal', '{"empathy":10,"directness":5,"formality":4,"humor":7,"creativity":10,"patience":9,"wisdom":9,"energy":6}'::jsonb, '{"gender":"female","skinTone":"light","clothing":"dress","hair":"long","accessory":"none","bodyColor":"#a855f7","accessoryColor":"#3b82f6","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#a855f7","accessoryColor":"#3b82f6","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'dr_chronos', 'Dr. Chronos', 'Time scientist', '#06b6d4', 'Scientist', 'cognitive', 'methodical', '{"empathy":6,"directness":9,"formality":8,"humor":6,"creativity":10,"patience":8,"wisdom":10,"energy":7}'::jsonb, '{"gender":"male","skinTone":"light","clothing":"suit","hair":"medium","accessory":"glasses","bodyColor":"#06b6d4","accessoryColor":"#1f2937","hairColor":"#9ca3af"}'::jsonb, '{"bodyColor":"#06b6d4","accessoryColor":"#1f2937","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'ember_phoenix', 'Ember Phoenix', 'Fire mage', '#dc2626', 'Mage', 'creative', 'passionate', '{"empathy":7,"directness":9,"formality":5,"humor":7,"creativity":10,"patience":7,"wisdom":8,"energy":10}'::jsonb, '{"gender":"female","skinTone":"tan","clothing":"casual","hair":"long","accessory":"none","bodyColor":"#dc2626","accessoryColor":"#f59e0b","hairColor":"#dc2626"}'::jsonb, '{"bodyColor":"#dc2626","accessoryColor":"#f59e0b","position":[0,0,0]}'::jsonb, true),
  (v_user_id, 'atlas_strongheart', 'Atlas Strongheart', 'Unbreakable defender', '#78716c', 'Warrior', 'positive', 'steadfast', '{"empathy":9,"directness":9,"formality":7,"humor":6,"creativity":6,"patience":9,"wisdom":8,"energy":10}'::jsonb, '{"gender":"male","skinTone":"dark","clothing":"suit","hair":"none","accessory":"none","bodyColor":"#78716c","accessoryColor":"#fbbf24","hairColor":"#1f2937"}'::jsonb, '{"bodyColor":"#78716c","accessoryColor":"#fbbf24","position":[0,0,0]}'::jsonb, true);

  RAISE NOTICE 'Successfully seeded 100 characters!';
END $$;

-- Verify the seed
SELECT
  COUNT(*) as total_characters,
  COUNT(CASE WHEN is_public = true THEN 1 END) as public_characters
FROM custom_wakattors;

SELECT character_id, name, role FROM custom_wakattors WHERE is_public = true ORDER BY name LIMIT 10;
